import educational from '../knowledge/educational.json' with { type: 'json' };
import sales from '../knowledge/sales.json' with { type: 'json' };
import story from '../knowledge/story.json' with { type: 'json' };
import motivation from '../knowledge/motivation.json' with { type: 'json' };
const PROFILES=Object.freeze({educational,sales,story,motivation});
export function getProducerProfile(goal){const key=String(goal||'').trim().toLowerCase();if(!PROFILES[key])throw new Error('Please choose what kind of video you are creating.');return structuredClone(PROFILES[key]);}
export function createProducerDecision({goal,transcript,meaningAnalysis,duration}){const profile=getProducerProfile(goal);return{version:2,goal:profile.id,label:profile.label,purpose:profile.purpose,pacing:profile.pacing,captions:profile.captions,camera:profile.camera,visuals:{...profile.visuals,opportunities:plan({transcript,meaningAnalysis,duration,profile})},principles:profile.principles};}
function plan({transcript,meaningAnalysis,duration,profile}){const out=[];const rules=[[/\b(three|3)\b.*\b(steps|reasons|ways|things|solutions)\b/i,'three-step-diagram','A structured list can be understood faster visually.'],[/\b(grow|growth|increase|rising|upward|profit|revenue)\b/i,'growth-graph','A growth idea is clearer when visualised.'],[/\b(before|after|instead|versus|vs\.?|compare|difference)\b/i,'comparison-card','The speaker is comparing two states or choices.'],[/\b(percent|percentage|%|rand|r\d+|number|statistic|data)\b/i,'proof-stat','A number or claim can be reinforced visually.'],[/\b(first|then|next|finally|process|timeline)\b/i,'timeline','The speaker is explaining a sequence.']];for(const a of meaningAnalysis){for(const [rx,type,reason] of rules){if(rx.test(a.text||'')){out.push({start:r(a.start),end:r(Math.min(a.end,a.start+3.2)),type:profile.visuals.preferredTypes.includes(type)?type:profile.visuals.preferredTypes[0],reason,sourceText:a.text,confidence:Math.min(.95,.55+a.score*.06)});break;}}}if(out.length<profile.visuals.minimumOpportunities){for(const a of meaningAnalysis.filter(x=>x.score>=2).sort((x,y)=>y.score-x.score)){if(out.some(x=>Math.abs(x.start-a.start)<4))continue;out.push({start:r(a.start),end:r(Math.min(a.end,a.start+2.8)),type:profile.visuals.preferredTypes[out.length%profile.visuals.preferredTypes.length],reason:'A meaningful point benefits from visual reinforcement.',sourceText:a.text,confidence:.62});if(out.length>=profile.visuals.minimumOpportunities)break;}}return out.filter(x=>x.start<duration).sort((a,b)=>a.start-b.start).slice(0,6);}
const r=v=>Math.round(Number(v||0)*1000)/1000;
