begin;

create table if not exists public.ica_member_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'ICA Member',
  monthly_video_allowance integer not null default 5 check (monthly_video_allowance between 0 and 1000),
  videos_used integer not null default 0 check (videos_used >= 0),
  period_start date not null default date_trunc('month', now())::date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ica_usage_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null check (status in ('claimed', 'completed', 'failed')),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  output_count integer not null default 0 check (output_count >= 0),
  error_code text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists ica_usage_events_user_started_idx
  on public.ica_usage_events (user_id, started_at desc);

alter table public.ica_member_profiles enable row level security;
alter table public.ica_usage_events enable row level security;
revoke all on public.ica_member_profiles from anon, authenticated;
revoke all on public.ica_usage_events from anon, authenticated;
grant all on public.ica_member_profiles to service_role;
grant all on public.ica_usage_events to service_role;
grant usage, select on sequence public.ica_usage_events_id_seq to service_role;

create or replace function public.ica_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.ica_member_profiles (user_id, display_name)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      nullif(new.raw_user_meta_data ->> 'name', ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'ICA Member'
    )
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_ica_auth_user_created on auth.users;
create trigger on_ica_auth_user_created
  after insert on auth.users
  for each row execute function public.ica_handle_new_user();

insert into public.ica_member_profiles (user_id, display_name)
select id,
       coalesce(
         nullif(raw_user_meta_data ->> 'display_name', ''),
         nullif(raw_user_meta_data ->> 'name', ''),
         nullif(split_part(coalesce(email, ''), '@', 1), ''),
         'ICA Member'
       )
from auth.users
on conflict (user_id) do nothing;

create or replace function public.ica_reset_period(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.ica_member_profiles
  set videos_used = 0,
      period_start = date_trunc('month', now())::date,
      updated_at = now()
  where user_id = p_user_id
    and period_start < date_trunc('month', now())::date;
end;
$$;

create or replace function public.ica_get_member_summary(p_user_id uuid)
returns table (
  display_name text,
  monthly_video_allowance integer,
  videos_used integer,
  videos_remaining integer,
  period_start date,
  is_active boolean
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.ica_reset_period(p_user_id);
  return query
  select p.display_name,
         p.monthly_video_allowance,
         p.videos_used,
         greatest(p.monthly_video_allowance - p.videos_used, 0),
         p.period_start,
         p.is_active
  from public.ica_member_profiles p
  where p.user_id = p_user_id;
end;
$$;

create or replace function public.ica_claim_video_allowance(
  p_user_id uuid,
  p_job_id uuid,
  p_duration_seconds integer default 0
)
returns table (
  allowed boolean,
  videos_remaining integer,
  reason text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  profile public.ica_member_profiles%rowtype;
begin
  perform public.ica_reset_period(p_user_id);

  select * into profile
  from public.ica_member_profiles
  where user_id = p_user_id
  for update;

  if not found then
    return query select false, 0, 'profile-missing'::text;
    return;
  end if;

  if not profile.is_active then
    return query select false, 0, 'member-inactive'::text;
    return;
  end if;

  if exists (select 1 from public.ica_usage_events where job_id = p_job_id) then
    return query select true, greatest(profile.monthly_video_allowance - profile.videos_used, 0), 'already-claimed'::text;
    return;
  end if;

  if profile.videos_used >= profile.monthly_video_allowance then
    return query select false, 0, 'allowance-exhausted'::text;
    return;
  end if;

  update public.ica_member_profiles
  set videos_used = videos_used + 1,
      updated_at = now()
  where user_id = p_user_id;

  insert into public.ica_usage_events (
    job_id, user_id, status, duration_seconds
  ) values (
    p_job_id, p_user_id, 'claimed', greatest(coalesce(p_duration_seconds, 0), 0)
  );

  return query
  select true,
         greatest(profile.monthly_video_allowance - profile.videos_used - 1, 0),
         'claimed'::text;
end;
$$;

create or replace function public.ica_finish_video_job(
  p_job_id uuid,
  p_status text,
  p_output_count integer default 0,
  p_error_code text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  usage_row public.ica_usage_events%rowtype;
begin
  if p_status not in ('completed', 'failed') then
    raise exception 'Unsupported ICA job status';
  end if;

  select * into usage_row
  from public.ica_usage_events
  where job_id = p_job_id
  for update;

  if not found then return; end if;
  if usage_row.status in ('completed', 'failed') then return; end if;

  if p_status = 'failed' then
    update public.ica_member_profiles
    set videos_used = greatest(videos_used - 1, 0),
        updated_at = now()
    where user_id = usage_row.user_id;
  end if;

  update public.ica_usage_events
  set status = p_status,
      output_count = greatest(coalesce(p_output_count, 0), 0),
      error_code = p_error_code,
      completed_at = now()
  where job_id = p_job_id;
end;
$$;

revoke all on function public.ica_handle_new_user() from public, anon, authenticated;
revoke all on function public.ica_reset_period(uuid) from public, anon, authenticated;
revoke all on function public.ica_get_member_summary(uuid) from public, anon, authenticated;
revoke all on function public.ica_claim_video_allowance(uuid, uuid, integer) from public, anon, authenticated;
revoke all on function public.ica_finish_video_job(uuid, text, integer, text) from public, anon, authenticated;
grant execute on function public.ica_get_member_summary(uuid) to service_role;
grant execute on function public.ica_claim_video_allowance(uuid, uuid, integer) to service_role;
grant execute on function public.ica_finish_video_job(uuid, text, integer, text) to service_role;

commit;
